### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by lfarah** [doubleencore/XcodeIssueGenerator#11]
Getting this error when running the ```XcodeIssueGenerator.xcodeproj```:
> /Users/lucasfarah/Downloads/XcodeIssueGenerator-master/XcodeIssueGenerator/main.swift:88: error: // CRITICAL: Dogfooding the issue generator with a CRITICAL.
Program ended with exit code: 1

**Comment by soolwan** [comment]
Hi, that's sort of working as expected because I left a // CRITICAL in the main.swift file and I have environment variables set like this:
<img width="762" alt="screen shot 2016-05-15 at 11 11 34 am" src="https://cloud.githubusercontent.com/assets/217295/15275638/50637816-1a8e-11e6-8ec2-209f2b8c9710.png">

But that's not a good way to leave the project so I'll remove those comments that are error-producing. Thanks!

**Comment by soolwan** [comment]
This commit has that change: 8856aaf970f9a1df1b5a2604aed721a5f45d69b0
